# Generated by Django 4.2.3 on 2023-07-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allsongs',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_title', models.TextField()),
                ('song_category', models.CharField(max_length=50)),
                ('song_file', models.FileField(upload_to='songs/')),
            ],
        ),
    ]
